### ISSUE TITLE
Top navigation bar's blur effect doesn't work on Safari

### ISSUE THREAD

**Issue by YektaDev** [varabyte/kobweb-site#10]
Hi,

Noticed something with the header blur effect, as you can guess from the title. It works on Chromium-based browsers but on Safari, it just shows a dark overlay. Figured it's worth noting.

**Comment by bitspittle** [comment]
So embarrassed I didn't see this issue until now. Sorry for the late reply.

Actually, we fixed a bug in Kobweb a few weeks back to address this issue. I just rebuilt the site and deployed a new version, so the blur should be working on Safari now!
